### PR TITLE
Avoid global buffer overflow

### LINKED ISSUE #32: Global-buffer-overflow when compiling with SANITIZER=1
When I `make` with `SANITIZER=1` and run the trace `trace-17-complexity.cmd`, the result shows that there exist global buffer overflow:
```shell
$ ./qtest -f traces/trace-17-complexity.cmd
cmd> # Test if q_insert_tail and q_size is constant time complexity
cmd> option simulation 1
=================================================================
==13327==ERROR: AddressSanitizer: global-buffer-overflow on address 0x555aa21519c0 at pc 0x555aa1f4282c bp 0x7ffde162b170 sp 0x7ffde162b160
READ of size 4 at 0x555aa21519c0 thread T0
    #0 0x555aa1f4282b in do_option_cmd /home/jtsai/linux2020/lab0-c/console.c:368
    #1 0x555aa1f41448 in interpret_cmda /home/jtsai/linux2020/lab0-c/console.c:220
    #2 0x555aa1f41e4c in interpret_cmd /home/jtsai/linux2020/lab0-c/console.c:243
    #3 0x555aa1f42b35 in cmd_select /home/jtsai/linux2020/lab0-c/console.c:571
    #4 0x555aa1f42f52 in run_console /home/jtsai/linux2020/lab0-c/console.c:630
    #5 0x555aa1f4006b in main /home/jtsai/linux2020/lab0-c/qtest.c:770
    #6 0x7fd4aa4abb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #7 0x555aa1f3d7d9 in _start (/home/jtsai/linux2020/lab0-c/qtest+0x67d9)

0x555aa21519c1 is located 0 bytes to the right of global variable 'simulation' defined in 'console.c:20:6' (0x555aa21519c0) of size 1
  'simulation' is ascii string ''
SUMMARY: AddressSanitizer: global-buffer-overflow /home/jtsai/linux2020/lab0-c/console.c:368 in do_option_cmd
Shadow bytes around the buggy address:
  0x0aabd44222e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aabd44222f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aabd4422300: 00 00 00 00 00 00 00 00 00 00 00 00 f9 f9 f9 f9
  0x0aabd4422310: 00 f9 f9 f9 f9 f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9
  0x0aabd4422320: 00 f9 f9 f9 f9 f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9
=>0x0aabd4422330: 00 f9 f9 f9 f9 f9 f9 f9[01]f9 f9 f9 f9 f9 f9 f9
  0x0aabd4422340: 00 00 00 00 01 f9 f9 f9 f9 f9 f9 f9 04 f9 f9 f9
  0x0aabd4422350: f9 f9 f9 f9 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aabd4422360: 00 00 00 00 00 00 00 00 00 00 00 00 00 f9 f9 f9
  0x0aabd4422370: f9 f9 f9 f9 01 f9 f9 f9 f9 f9 f9 f9 01 f9 f9 f9
  0x0aabd4422380: f9 f9 f9 f9 04 f9 f9 f9 f9 f9 f9 f9 00 f9 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==13327==ABORTING

```

### PR DESCRIPTION
**Pull request by eecheng87**
To avoid global buffer overflow when compiling with SANITIZER=1,
this commit replaces bool type with integer type.

close #32

### CODE REVIEW

File: console.c [hunk 1]
```diff
@@ -18,7 +18,7 @@
 #include "report.h"
 
 /* Some global values */
-bool simulation = false;
+int simulation = false;
```
Comment (jserv) [inline console.c:21]: Should be set to `0` instead of `false`.
